algoritmo "exemplo_estrutura_repeticao_para"
// Função : Utilizando conceito de estrutura de repetição (comando PARA)
// Autor  : André Olímpio
// Data   : 30/08/2019
// Seção de Declarações 
var
   nome: caractere
   contador: inteiro
inicio
// Seção de Comandos
   escreva("Digite o nome: ")
   leia(nome)
   para contador de 1 ate 10 faca
        escreval(contador,"-",nome)
   fimpara
fimalgoritmo
