algoritmo "exemplo_estrutura_repeticao_enquanto"
// Função : Utilizando conceito de estrutura de repetição (comando ENQUANTO)
// Autor  : André Olímpio
// Data   : 30/08/2019
// Seção de Declarações 
var
   nome: caractere
   contador: inteiro
inicio
// Seção de Comandos
   escreva("Digite o nome: ")
   leia(nome)
   contador <- 1
   enquanto (contador <= 10) faca
           escreval(contador,"-",nome)
           contador <- contador + 1
   fimenquanto
fimalgoritmo
